name: ${project.name}
version: ${project.version}
author: magicmq
main: dev.magicmq.pyspigot.PySpigot
load: STARTUP
api-version: '1.13'
softdepend: [ProtocolLib, PlaceholderAPI]
commands:
  pyspigot:
    description: The main command for PySpigot.
    aliases: [ps]